### ISSUE TITLE
robot.loadVariablesFromArgumentsFile does not resolve ${workspaceFolder} (VS Code)

### ISSUE THREAD

**Issue by johndoorzon** [robocorp/robotframework-lsp#669]
**Describe the bug**
When I put the following line in my settings.json:
"robot.loadVariablesFromArgumentsFile": "${workspaceFolder}/arguments.ini",

I still get errors that variables cannot be resolved.

When I substituted the complete path, it worked correctly, so it seems that the variable ${workspaceFolder} is not resolved correctly

**To Reproduce**
1. create an argument file "arguments.ini" in the root of your project with at least one variable that is used, but not resolved in a test
2. add the following line to settings.json:
"robot.loadVariablesFromArgumentsFile": "${workspaceFolder}/arguments.ini"

**Expected behavior**
All variables in the project are resolved

**Comment by seizu** [comment]
I have a similar problem, I think most of these variables [https://code.visualstudio.com/docs/editor/variables-reference](url) have not been substituted.

**Comment by seizu** [comment]
@johndoorzon try ${workspaceRoot} instead of ${workspaceFolder}

**Comment by johndoorzon** [comment]
@seizu Nope, tried that one also

**Comment by lukspa** [comment]
We also have similar problem, in our tests we use such construction:
`Variables   ../../env/${env}.yaml`

where ${env} is environment name (DEV, TEST, PROD).
Path points to file with env specific vars.

It worked fine in version 0.42.0
Broke in version 0.43.0, where ${env} stopped being resolved.
Currently in version 0.46.0, ${env} is resolved, but vars from file aren't.

**Comment by fabioz** [comment]
@lukspa this seems like a different issue. Can you report it separately?

Also, can you provide a sample project so that I can make sure I can reproduce the same thing you're seeing?

**Comment by johndoorzon** [comment]
[robocorp.zip](https://github.com/robocorp/robotframework-lsp/files/8642095/robocorp.zip)

**Comment by fabioz** [comment]
> I have a similar problem, I think most of these variables [variables-reference](https://code.visualstudio.com/docs/editor/variables-reference) have not been substituted.
> 
> e.g. in settings `"robot.variables": { "EXECDIR": "${fileDirname}" }`

@seizu note that not all variables from https://code.visualstudio.com/docs/editor/variables-reference are actually resolved.

See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-specify-a-variable-needed-to-resolve-some-library-or-resource-import for the variables that are actually resolved.

If you do have a need for some additional variable, please create a separate issue to track that.

**Comment by johndoorzon** [comment]
Why is this closed? ${workspaceFolder} is still not resolved when using it in loadVariablesFromArgumentsFile.
Therefore the variables in my argument file are not resolved statically.
Tested with 0.47.2

**Comment by JanDubcak** [comment]
This is also issue for me. When I make launch configuration with ${workspaceFolder}/path_to_argument_file, I have no issues with running it from left panel debug view.
But if I try to run same test with same configuration from opened test case, it looks like arguments (--variablefile xyz) in argumentfile are not parsed / used. 

![rf_argumentfile](https://user-images.githubusercontent.com/65766592/181741335-ab685ea8-ba64-4dbc-aa2b-5b5acbcd14bb.png)

**Comment by fabioz** [comment]
@JanDubcak you need to customize the launch for the code lens on this case following: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-configure-the-launch-from-a-code-lensshortcut

p.s.: if you still can't get it to work, please create a new issue.

**Comment by JanDubcak** [comment]
@fabioz Hi, thanks for link to FAQ, I have seen only /docs/config.md where it does not mention that launch has to have exact `"name": "Robot Framework: Launch template"`. It works now both from debug view and from code as well. 
If needed I can update and prepare PR with updated /docs/config.md with this example. It would be easier to find imho.
Great thanks once again!
